#!/usr/bin/env bash
# Script installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
