#!/usr/bin/env bash
# This script installs nginx on my server
# And configures the server so that it redirects to another page

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
to_replace="\\\trewrite ^/redirect_me http://konoma.tech permanent;"
sudo sed -i "26i $to_replace" /etc/nginx/sites-available/default

sudo service nginx restart
