#!/usr/bin/env bash
# Script configures Nginx server cat etc/nginx/sites-enabled/default

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/codesinpink.hashnode.dev permanent;"
sudo sed -i "s/server_name _;/$to_replace/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart

# codesinpink.hashnode.dev
# www.youtube.com/@ALXAfrica
