#!/usr/bin/env bash
# Script configures the Nginx server to have a custom 404 page
# which contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
to_replace="server_name _;\n\trewrite ^\/redirect_me http:\/\/konoma.tech permanent;"
sudo sed -i "s/server_name _;/$to_replace/" /etc/nginx/sites-enabled/default

# redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
to_replace_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$to_replace_404/" /etc/nginx/sites-enabled/default

sudo service nginx restart
