#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www
echo 'Hello World!' |sudo tee  /var/www/html/index.html

echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
for_replace="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me http:\/\/konoma.tech permanent;"
sudo sed -i "s/server_name _;/$for_replace/" /etc/nginx/sites-enabled/default

for_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$for_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
