#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www

sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sudo sed -i "/^\sserver_name.*/a\ \trewrite ^\/redirect_me http:\/\/konoma.tech permanent;" /etc/nginx/sites-available/default
sudo sed -i "/^\slocation.*/i\ \terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default
sudo sed -i "/^\slocation \/ {/i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
