#!/usr/bin/env bash
# Installing and configuring HAproxy on lb-01 server.
# Configuring HAproxy so that it send traffic to web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install haproxy

#config file edit
server_config=\
"
frontend  haproxynode
        bind *:80
        mode http
        default_backend backendnodes
backend backendnodes
        balance roundrobin
        server 151805-web-01 52.91.182.106:80 check
        server 151805-web-02 35.174.209.196:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
