#!/usr/bin/env bash
# Bash script that configures an Ubuntu server requiring the following:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Resolve Docker: cannot rename /etc/sedl8ySxL
cp /etc/hosts ~/hosts.new

# Resolving IP addresses and adding them to ~/hosts.new
echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" > ~/hosts.new

# Resolve Docker: cannot rename /etc/sedl8ySxL
cp -f ~/hosts.new /etc/hosts
